name: multi_image_picker2
description: Flutter plugin that allows you to display multi image picker on iOS and Android.
version: 6.0.0
homepage: https://github.com/artflutter/multi_image_picker2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.vitanov.multiimagepicker
        pluginClass: MultiImagePickerPlugin
      ios:
        pluginClass: MultiImagePicker2Plugin

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"
